import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import fs from "node:fs";
import path from "node:path";

type DeploymentJson = {
  address: string;
  abi: unknown;
};

function toTsStringLiteral(value: string): string {
  return `'${value.replace(/'/g, "\\'")}'`;
}

task("task:sync-ui-abi", "Copies deployments/<network>/FHEOracle.json ABI+address into ui/src/config/contracts.ts")
  .addOptionalParam("networkName", "Hardhat-deploy network folder name (defaults to hre.network.name)")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const networkName = (taskArguments.networkName as string | undefined) ?? hre.network.name;
    const deploymentPath = path.join(hre.config.paths.root, "deployments", networkName, "FHEOracle.json");
    const outPath = path.join(hre.config.paths.root, "ui", "src", "config", "contracts.ts");

    if (!fs.existsSync(deploymentPath)) {
      throw new Error(`Missing deployment file: ${deploymentPath}\nRun: npx hardhat deploy --network ${networkName}`);
    }

    const raw = fs.readFileSync(deploymentPath, "utf8");
    const parsed = JSON.parse(raw) as DeploymentJson;

    if (!parsed.address || !parsed.abi) {
      throw new Error(`Invalid deployment JSON: ${deploymentPath}`);
    }

    const file = `// Auto-generated by \`npx hardhat task:sync-ui-abi --network ${networkName}\`
// Do not edit by hand.
export const CONTRACT_ADDRESS = ${toTsStringLiteral(parsed.address)};
export const CONTRACT_ABI = ${JSON.stringify(parsed.abi, null, 2)} as const;
`;

    fs.writeFileSync(outPath, file, "utf8");
    console.log(`Synced ABI+address to ${outPath}`);
  });

